name: Build
on: [pull_request]

jobs:
  container-job:
    env:
      OED_DB_USER: test
      OED_DB_PASSWORD: travisTest
      OED_DB_DATABASE: travis_ci_dummy
      OED_DB_TEST_DATABASE: travis_ci_test
      OED_DB_HOST: postgres
      OED_DB_PORT: 5432
      OED_TOKEN_SECRET: travis
      OED_SERVER_PORT: 3000
      DOCKER_COMPOSE_VERSION: 1.27.4
      POSTGRES_PASSWORD: travisTest

    runs-on: ubuntu-latest
    container: node:14

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: travisTest
          POSTGRES_DB: travis_ci_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

        ports:
          - 5432:5432

    steps:
      # see: https://github.com/actions/checkout/issues/335
      - name: upgrade git
        run: |
          apt-get update && apt-get -y dist-upgrade \
          && apt-get install -y software-properties-common \
          apt-get update && apt-get -y dist-upgrade \
          && add-apt-repository -y ppa:git-core/ppa \
          apt-get update && apt-get -y dist-upgrade \
          && apt-get install -y git

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Connect to PostgreSQL
        run: node client.js
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          OED_DB_TEST_DATABASE: travis_ci_test
          POSTGRES_PASSWORD: travisTest

      - name: node tests
        run: |
          npm run check:header
          npm run check:typescript
          npm run check:types
          npm run check:lint
          npm run test
